[project]
name = "sat-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Christian Meynen", email = "christianmeynen@msn.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.12.2",
    "dbt-postgres>=1.11.0",
    "psycopg[binary]>=3.3.4",
    "pyarrow>=25.0.1",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "requests>=2.34.2",
    "spacedatastandards-org>=23.3.3.0.3.7",
]

[project.scripts]
sat-tracker-ingest = "sat_tracker.cli:main"
sat-tracker-load = "sat_tracker.cli:load"
sat-tracker-transform = "sat_tracker.cli:transform"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]
